version: '3'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: movie
      MONGO_INITDB_ROOT_PASSWORD: movie
    networks:
      - movie
  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongo
    networks:
      - movie
  rate-service:
    build: ../rate-service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - movie

networks:
  movie:
